00000100:00000400:0.0F:1579565381.692550:0:3424:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for slow reply: [sent 1579565374/real 1579565374]  req@ffff941e04825200 x1656284885625456/t0(0) o400->lustre-MDT0000-mdc-ffff941e7bb3c000@10.29.161.11@tcp:12/10 lens 224/224 e 0 to 1 dl 1579565381 ref 1 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:02000400:0.0:1579565381.692612:0:3424:0:(import.c:179:ptlrpc_set_import_discon()) lustre-MDT0000-mdc-ffff941e7bb3c000: Connection to lustre-MDT0000 (at 10.29.161.11@tcp) was lost; in progress operations using this service will wait for recovery to complete
00000100:00080000:0.0:1579565381.692621:0:3424:0:(import.c:188:ptlrpc_set_import_discon()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from FULL to DISCONN
00000100:00080000:0.0:1579565381.692626:0:3424:0:(import.c:418:ptlrpc_pinger_force()) lustre-MDT0000_UUID: waking up pinger s:DISCONN
00000100:00080000:0.0:1579565381.692656:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level DISCONN/3 force 1 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579565381.692662:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579565381.692664:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565381.692671:0:3426:0:(import.c:524:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: connect to NID 10.29.161.11@tcp last attempt 4302743692
00000100:00080000:0.0:1579565381.692678:0:3426:0:(import.c:602:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: import ffff941e4ea7d800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000100:00000400:0.0:1579565382.692534:0:3424:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for slow reply: [sent 1579565374/real 1579565374]  req@ffff941e04824600 x1656284885625488/t0(0) o400->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 224/224 e 0 to 1 dl 1579565382 ref 1 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:02000400:0.0:1579565382.692567:0:3424:0:(import.c:179:ptlrpc_set_import_discon()) lustre-OST0001-osc-ffff941e7bb3c000: Connection to lustre-OST0001 (at 10.24.85.194@tcp) was lost; in progress operations using this service will wait for recovery to complete
00000100:00080000:0.0:1579565382.692582:0:3424:0:(import.c:188:ptlrpc_set_import_discon()) ffff941e00074000 lustre-OST0001_UUID: changing import state from FULL to DISCONN
00000100:00080000:0.0:1579565382.692588:0:3424:0:(import.c:418:ptlrpc_pinger_force()) lustre-OST0001_UUID: waking up pinger s:DISCONN
00000100:00080000:0.0:1579565382.692617:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 1 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579565382.692623:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565382.692625:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565382.692632:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4303518731
00000100:00080000:0.0:1579565382.692640:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000100:00000400:0.0:1579565387.693759:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for slow reply: [sent 1579565381/real 1579565381]  req@ffff941e04825200 x1656284885625520/t0(0) o38->lustre-MDT0000-mdc-ffff941e7bb3c000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579565387 ref 1 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565387.693795:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565387.693799:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00000400:0.0:1579565388.693586:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for slow reply: [sent 1579565382/real 1579565382]  req@ffff941e04824600 x1656284885625536/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565388 ref 1 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565388.693622:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565388.693626:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000800:00000100:0.0:1579565404.742552:0:3419:0:(socklnd_cb.c:2282:ksocknal_find_timed_out_conn()) A connection with 12345-10.24.85.194@tcp (10.24.85.194:988) timed out; the network or node may be down.
00000100:00080000:0.0:1579565407.696227:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565407.696236:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579565407.696239:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565407.696249:0:3426:0:(import.c:524:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: connect to NID 10.29.161.11@tcp last attempt 4304200740
00000100:00080000:0.0:1579565407.696253:0:3426:0:(import.c:568:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: tried all connections, increasing latency to 6s
00000100:00080000:0.0:1579565407.696260:0:3426:0:(import.c:602:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: import ffff941e4ea7d800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000100:00080000:0.0:1579565407.696278:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565407.696283:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565407.696285:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565407.696291:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304201740
00000100:00080000:0.0:1579565407.696293:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 6s
00000100:00080000:0.0:1579565407.696298:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565409.364811:0:3415:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1022 -> 10.24.85.194/988
00000400:00000100:0.0:1579565409.364836:0:3415:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565409.364850:0:3415:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565409.364878:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565407/real 1579565409]  req@ffff941e04825500 x1656284885625600/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565418 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565409.364927:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565409.364936:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00000400:0.0:1579565418.696623:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for slow reply: [sent 1579565407/real 1579565407]  req@ffff941e04825200 x1656284885625568/t0(0) o38->lustre-MDT0000-mdc-ffff941e7bb3c000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579565418 ref 1 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565418.696659:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565418.696663:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000800:00000100:0.0:1579565431.742556:0:3419:0:(socklnd_cb.c:2282:ksocknal_find_timed_out_conn()) A connection with 12345-10.29.161.11@tcp (10.29.161.11:988) timed out; the network or node may be down.
00000100:00080000:0.0:1579565432.695872:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565432.695881:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579565432.695884:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565432.695894:0:3426:0:(import.c:524:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: connect to NID 10.29.161.11@tcp last attempt 4304226743
00000100:00080000:0.0:1579565432.695898:0:3426:0:(import.c:568:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: tried all connections, increasing latency to 11s
00000100:00080000:0.0:1579565432.695905:0:3426:0:(import.c:602:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: import ffff941e4ea7d800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000100:00080000:0.0:1579565432.695923:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565432.695929:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565432.695930:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565432.695936:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304226743
00000100:00080000:0.0:1579565432.695938:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 11s
00000100:00080000:0.0:1579565432.695943:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565433.416761:0:3417:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1022 -> 10.24.85.194/988
00000400:00000100:0.0:1579565433.416792:0:3417:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565433.416806:0:3417:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565433.416842:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565432/real 1579565433]  req@ffff941e04824f00 x1656284885625680/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565448 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565433.416885:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565433.416889:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00000400:0.0:1579565448.701532:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for sent delay: [sent 1579565432/real 0]  req@ffff941e04825500 x1656284885625648/t0(0) o38->lustre-MDT0000-mdc-ffff941e7bb3c000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579565448 ref 2 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565457.695420:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level CONNECTING/4 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565457.695424:0:3426:0:(pinger.c:230:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: not pinging (in recovery or recovery disabled: CONNECTING)
00000100:00080000:0.0:1579565457.695426:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565457.695428:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565457.695429:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565457.695433:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304251743
00000100:00080000:0.0:1579565457.695434:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 16s
00000100:00080000:0.0:1579565457.695437:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565460.479892:0:3416:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1022 -> 10.24.85.194/988
00000400:00000100:0.0:1579565460.479919:0:3416:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565460.479933:0:3416:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565460.479961:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565457/real 1579565460]  req@ffff941e04825800 x1656284885625744/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565478 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565460.479986:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565460.479990:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00080000:0.0:1579565482.695470:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level CONNECTING/4 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565482.695479:0:3426:0:(pinger.c:230:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: not pinging (in recovery or recovery disabled: CONNECTING)
00000100:00080000:0.0:1579565482.695486:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565482.695495:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565482.695498:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565482.695507:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304276743
00000100:00080000:0.0:1579565482.695510:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 21s
00000100:00080000:0.0:1579565482.695518:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000800:00000100:0.0:1579565482.745239:0:3419:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.29.161.11@tcp
00000100:00080000:0.0:1579565482.745265:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565482.745270:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000400:00000100:0.0:1579565484.530831:0:3415:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1023 -> 10.24.85.194/988
00000400:00000100:0.0:1579565484.530855:0:3415:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565484.530869:0:3415:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565484.530900:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565482/real 1579565484]  req@ffff941e04824600 x1656284885625808/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565508 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565484.530925:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565484.530929:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00080000:0.0:1579565507.695599:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565507.695609:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579565507.695611:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565507.695620:0:3426:0:(import.c:524:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: connect to NID 10.29.161.11@tcp last attempt 4304251743
00000100:00080000:0.0:1579565507.695624:0:3426:0:(import.c:568:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: tried all connections, increasing latency to 16s
00000100:00080000:0.0:1579565507.695630:0:3426:0:(import.c:602:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: import ffff941e4ea7d800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000100:00080000:0.0:1579565507.695649:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565507.695654:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565507.695659:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565507.695665:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304301743
00000100:00080000:0.0:1579565507.695668:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 26s
00000100:00080000:0.0:1579565507.695672:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565508.578586:0:3417:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1023 -> 10.24.85.194/988
00000400:00000100:0.0:1579565508.578612:0:3417:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565508.578626:0:3417:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565508.578654:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565507/real 1579565508]  req@ffff941e04825200 x1656284885625888/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565538 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565508.578679:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565508.578683:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00000400:0.0:1579565528.704566:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has timed out for sent delay: [sent 1579565507/real 0]  req@ffff941e04825500 x1656284885625856/t0(0) o38->lustre-MDT0000-mdc-ffff941e7bb3c000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579565528 ref 2 fl Rpc:XN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565532.695624:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level CONNECTING/4 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565532.695633:0:3426:0:(pinger.c:230:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: not pinging (in recovery or recovery disabled: CONNECTING)
00000100:00080000:0.0:1579565532.695640:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565532.695645:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565532.695648:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565532.695656:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304326743
00000100:00080000:0.0:1579565532.695660:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 31s
00000100:00080000:0.0:1579565532.695667:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565535.701241:0:3416:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1023 -> 10.24.85.194/988
00000400:00000100:0.0:1579565535.701270:0:3416:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565535.701290:0:3416:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565535.701321:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565532/real 1579565535]  req@ffff941e04825800 x1656284885625952/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565568 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565535.701348:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565535.701352:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000100:00080000:0.0:1579565557.695547:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level CONNECTING/4 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565557.695556:0:3426:0:(pinger.c:230:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: not pinging (in recovery or recovery disabled: CONNECTING)
00000100:00080000:0.0:1579565557.695562:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565557.695568:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565557.695570:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565557.695579:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304351743
00000100:00080000:0.0:1579565557.695583:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 36s
00000100:00080000:0.0:1579565557.695590:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000800:00000100:0.0:1579565557.695700:0:3423:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.24.85.194@tcp
00000100:00000400:0.0:1579565557.695710:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565557/real 1579565557]  req@ffff941e04824f00 x1656284885626016/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565598 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565557.695732:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565557.695736:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
00000800:00000100:0.0:1579565558.742524:0:3419:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.29.161.11@tcp
00000100:00080000:0.0:1579565558.742560:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565558.742565:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000400:00000100:0.0:1579565559.960627:0:3418:0:(lib-socket.c:645:lnet_sock_connect()) Error -110 connecting 10.24.85.117/1021 -> 10.29.161.11/988
00000400:00000100:0.0:1579565559.960657:0:3418:0:(acceptor.c:118:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 took too long: that node may be hung or experiencing high load.
00000100:00080000:0.0:1579565582.695529:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565582.695539:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579565582.695542:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e4ea7d800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565582.695551:0:3426:0:(import.c:524:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: connect to NID 10.29.161.11@tcp last attempt 4304326743
00000100:00080000:0.0:1579565582.695555:0:3426:0:(import.c:568:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: tried all connections, increasing latency to 21s
00000100:00080000:0.0:1579565582.695562:0:3426:0:(import.c:602:import_select_connection()) lustre-MDT0000-mdc-ffff941e7bb3c000: import ffff941e4ea7d800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000100:00080000:0.0:1579565582.695581:0:3426:0:(pinger.c:217:ptlrpc_pinger_process_import()) 3d961b86-f0b7-97ab-251c-904f37ce09d3->lustre-OST0001_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 1
00000100:00080000:0.0:1579565582.695586:0:3426:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-OST0001_UUID: starting recovery
00000100:00080000:0.0:1579565582.695587:0:3426:0:(import.c:681:ptlrpc_connect_import()) ffff941e00074000 lustre-OST0001_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579565582.695593:0:3426:0:(import.c:524:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: connect to NID 10.24.85.194@tcp last attempt 4304376743
00000100:00080000:0.0:1579565582.695596:0:3426:0:(import.c:568:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: tried all connections, increasing latency to 41s
00000100:00080000:0.0:1579565582.695600:0:3426:0:(import.c:602:import_select_connection()) lustre-OST0001-osc-ffff941e7bb3c000: import ffff941e00074000 using connection 10.24.85.194@tcp/10.24.85.194@tcp
00000400:00000100:0.0:1579565585.700860:0:3417:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.24.85.117/1023 -> 10.24.85.194/988
00000400:00000100:0.0:1579565585.700886:0:3417:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.24.85.194@tcp at host 10.24.85.194 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579565585.700901:0:3417:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.24.85.117@tcp->10.24.85.194@tcp
00000100:00000400:0.0:1579565585.700935:0:3423:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579565582/real 1579565585]  req@ffff941e04825800 x1656284885626096/t0(0) o8->lustre-OST0001-osc-ffff941e7bb3c000@10.24.85.194@tcp:28/4 lens 520/544 e 0 to 1 dl 1579565628 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579565585.700960:0:3423:0:(import.c:1284:ptlrpc_connect_interpret()) ffff941e00074000 lustre-OST0001_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579565585.700964:0:3423:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-OST0001_UUID on 10.24.85.194@tcp failed (-110)
